//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketsBookingOnlineSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaDbContextEntities1 : DbContext
    {
        public CinemaDbContextEntities1()
            : base("name=CinemaDbContextEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Auditoriums> Auditoriums { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Creators> Creators { get; set; }
        public virtual DbSet<FilmGenres> FilmGenres { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Seances> Seances { get; set; }
        public virtual DbSet<Spots> Spots { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
