//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketsBookingOnlineSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservations()
        {
            this.Spots = new HashSet<Spots>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Spot { get; set; }
        public int SeanceId { get; set; }
        public int Row { get; set; }
        public System.DateTime Date { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Seances Seances { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spots> Spots { get; set; }
    }
}
